### ISSUE TITLE
Compilation of tests with trunk fails due to lack of JavaFileSource class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anne/google-gin#46]
```
Compilation of tests fails with current trunk due to this changes:
http://code.google.com/p/google-web-toolkit/source/detail?r=5166


[javac]
/home/kojot/dev/google/google-gin/test/com/google/gwt/inject/rebind/util/Abstrac
tUtilTester.java:32:
cannot find symbol
    [javac] symbol  : class JavaSourceFile                                

    [javac] location: package com.google.gwt.dev.javac                    

    [javac] import com.google.gwt.dev.javac.JavaSourceFile;
```

Original issue reported on code.google.com by `kojot...@gmail.com` on 17 Jun 2009 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Gin at present works with GWT 1.5/1.6/trunk, but the tests compile only against 
1.6.
The issue is there is no real API to let us test Generators like this, so we are
stuck depending on implementation details.
```

Original comment by `bsto...@google.com` on 18 Jun 2009 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
This will come up again, but for now I'd call it "works as intended". We'll try 
to
keep the tests in sync with the latest official GWT release.
```

Original comment by `aragos` on 25 Jun 2009 at 11:00
- Changed state: **WontFix**
